[package]
name = "rml_macros"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rml_core = { path = "../rml_core" }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
uuid = { version = "1.11.0", features = ["v4"] }
regex = "1.0"